name: Convert METIS ISO to Docker Image and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download aria2c
        run: |
          sudo systemctl start docker 
          sudo systemctl enable docker 
          sudo usermod -aG docker $USER
          newgrp docker
          mkdir -p rootfs unsquashfs

      - name: Download ISO
        run: |
          aria2c -o metis-linux.iso https://github.com/metis-os/Releases/releases/download/MetisLinux-20230613/metis-linux-runit-20230613-x86_64.iso
          file metis-linux.iso
          du -h metis-linux.iso
          sudo mount -o loop metis-linux.iso /mnt

      - name: Extract ISO
        run: |
          sudo unsquashfs -f -d unsquashfs/ /mnt/casper/filesystem.squashfs

      - name: Build Docker Image
        run: |
          sudo tar -C unsquashfs -c . | docker import - metis/v1
          docker images

